package session

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// Session persistence on Unix is delegated to tmux.
//
// The product's premise is that a session survives things that would kill a
// plain SSH shell — including the agent itself restarting (systemd
// `Restart=always` restarts it after a crash or an upgrade). Sessions live in
// the agent process, so without a holder outside it every restart would drop
// every session.
//
// On Unix that holder already exists and is battle-tested, so terminalX does
// not write its own: each session is a tmux session, and the PTY the agent
// owns hosts a tmux *client*. Restarting the agent kills the client, not the
// session; the new agent re-attaches. (Windows has no tmux — that gap is the
// product's whole reason to exist there — so it still needs the ptyhost split
// tracked in docs/04 §0.2.)
//
// Everything runs on a private tmux server (`-L terminalx`) with a generated
// config, so the user's own tmux server, sockets, keybindings and status line
// are untouched, and our config cannot be broken by theirs.

// TmuxServer is the private tmux socket name terminalX uses. $TX_TMUX_SERVER
// overrides it, which keeps tests (and a second agent on the same machine)
// off the socket a running agent owns.
const TmuxServer = "terminalx"

func tmuxServerName() string {
	if v := strings.TrimSpace(os.Getenv("TX_TMUX_SERVER")); v != "" {
		return v
	}
	return TmuxServer
}

// tmuxConf is written next to the agent config and passed with -f. The prefix
// key is removed because every keystroke belongs to the AI CLI: leaving C-b
// bound would swallow readline's backward-char. terminalX drives tmux through
// its CLI instead, so it needs no keybindings at all.
const tmuxConf = `# generated by terminalX — do not edit, it is rewritten on start
set -g prefix None
unbind-key -a
set -g status off
set -g history-limit 20000
set -g escape-time 0
set -g destroy-unattached off
set -g exit-empty off
set -g mouse off
# Claude Code asks for focus events when it detects tmux; without them its TUI
# cannot tell whether the pane is focused.
set -g focus-events on
set -g default-terminal "xterm-256color"
set -g set-titles off
set -g allow-passthrough on
setw -g aggressive-resize on
`

// PersistName is the tmux session name for a sid.
func PersistName(sid uint32) string { return "tx-" + strconv.FormatUint(uint64(sid), 10) }

// PersistSID parses a tmux session name produced by PersistName.
func PersistSID(name string) (uint32, bool) {
	rest, ok := strings.CutPrefix(name, "tx-")
	if !ok {
		return 0, false
	}
	n, err := strconv.ParseUint(rest, 10, 32)
	if err != nil {
		return 0, false
	}
	return uint32(n), true
}

// TmuxAvailable reports whether tmux can be used for session persistence.
func TmuxAvailable() bool {
	_, err := exec.LookPath("tmux")
	return err == nil
}

// WriteTmuxConf writes the generated tmux config under dir and returns its
// path. It is rewritten every start so an upgrade cannot leave stale options.
func WriteTmuxConf(dir string) (string, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("session: create %s: %w", dir, err)
	}
	path := filepath.Join(dir, "tmux.conf")
	if err := os.WriteFile(path, []byte(tmuxConf), 0o600); err != nil {
		return "", fmt.Errorf("session: write %s: %w", path, err)
	}
	return path, nil
}

// tmuxArgs prefixes a tmux invocation with the private server and config.
func tmuxArgs(conf string, args ...string) []string {
	base := []string{"-L", tmuxServerName()}
	if conf != "" {
		base = append(base, "-f", conf)
	}
	return append(base, args...)
}

// tmuxRun executes a tmux command and returns its combined output.
func tmuxRun(conf string, args ...string) ([]byte, error) {
	return exec.Command("tmux", tmuxArgs(conf, args...)...).CombinedOutput()
}

// TmuxHasSession reports whether the named session exists on our server.
func TmuxHasSession(conf, name string) bool {
	_, err := tmuxRun(conf, "has-session", "-t", "="+name)
	return err == nil
}

// TmuxSessions lists the sids of the terminalX sessions currently alive.
func TmuxSessions(conf string) []uint32 {
	out, err := tmuxRun(conf, "list-sessions", "-F", "#{session_name}")
	if err != nil {
		return nil // no server running: no sessions, not an error
	}
	var sids []uint32
	for _, line := range strings.Split(string(out), "\n") {
		if sid, ok := PersistSID(strings.TrimSpace(line)); ok {
			sids = append(sids, sid)
		}
	}
	return sids
}

// TmuxKill destroys a session, ending the processes inside it.
func TmuxKill(conf, name string) error {
	if !TmuxHasSession(conf, name) {
		return nil
	}
	if out, err := tmuxRun(conf, "kill-session", "-t", "="+name); err != nil {
		return fmt.Errorf("session: tmux kill-session %s: %w: %s", name, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// TmuxCapture returns the last lines of a session's scrollback with escape
// sequences preserved, used to seed the ring buffer when re-adopting.
func TmuxCapture(conf, name string, lines int) []byte {
	// A pane target is session:window.pane; "=name:" pins the session name to
	// an exact match and lets tmux pick its active pane. Plain "=name" is a
	// session target and capture-pane rejects it.
	out, err := tmuxRun(conf, "capture-pane", "-p", "-e", "-J",
		"-S", "-"+strconv.Itoa(lines), "-t", "="+name+":")
	if err != nil {
		return nil
	}
	// capture-pane emits LF; a terminal needs CRLF.
	return []byte(strings.ReplaceAll(strings.TrimRight(string(out), "\n"), "\n", "\r\n"))
}

// tmuxLaunch builds the argv that attaches to the session, creating it with
// the given shell if it does not exist yet (-A). -x/-y only apply on create.
//
// The shell runs under a tiny sh wrapper that records its exit status. The
// process terminalX owns is the tmux *client*, whose status says nothing
// about the shell, so without the wrapper every session would report "exited
// (code 0)" however it ended.
func tmuxLaunch(conf, name string, cols, rows uint16, cwd, shell string, shellArgs []string, exitFile string) []string {
	args := tmuxArgs(conf, "new-session", "-A", "-s", name,
		"-x", strconv.Itoa(int(cols)), "-y", strconv.Itoa(int(rows)))
	if cwd != "" {
		args = append(args, "-c", cwd)
	}
	args = append(args, "--")
	if exitFile == "" {
		return append(append(args, shell), shellArgs...)
	}
	script := `"$@"; s=$?; printf %d "$s" > ` + shQuote(exitFile) + `; exit "$s"`
	args = append(args, "/bin/sh", "-c", script, "tx-session", shell)
	return append(args, shellArgs...)
}

// shQuote quotes a path for the /bin/sh wrapper above.
func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// readExitFile returns the shell's exit status recorded by the wrapper. The
// file is removed so a later generation of the same session cannot read a
// stale status.
func readExitFile(path string) (int32, bool) {
	if path == "" {
		return 0, false
	}
	b, err := os.ReadFile(path)
	_ = os.Remove(path)
	if err != nil {
		return 0, false
	}
	n, err := strconv.Atoi(strings.TrimSpace(string(b)))
	if err != nil {
		return 0, false
	}
	return int32(n), true
}
